#!/bin/bash
echo "window.APP_CONFIG = { \
  NAVER_MAP_CLIENT_ID: '$NAVER_MAP_CLIENT_ID', \
  KAKAO_CLIENT_ID: '$KAKAO_CLIENT_ID', \
  NAVER_CLIENT_ID: '$NAVER_CLIENT_ID', \
  GOOGLE_CLIENT_ID: '$GOOGLE_CLIENT_ID', \
  OAUTH_REDIRECT_URI: '$OAUTH_REDIRECT_URI', \
  SUCCESS_REDIRECT: '$SUCCESS_REDIRECT' \
};" > REMS/src/main/resources/static/config.js